on-player-join:
    enabled: true
    rules:
    - 'Welcome to the server'
rules:
    1:
    - 'these'
    - 'are'
    - 'example'
    - 'rules'
    3:
    - 'this page is called 3 but is the second page'
    2:
    - 'this page is called'
    - '2 but is the third'
    - 'page'
